export enum WolfIcons {

	CHECK_CIRCLE = 'CHECK_CIRCLE',
	MEGAPHONE = 'MEGAPHONE',
	EXCLAMATION_CIRCLE = 'EXCLAMATION_CIRCLE',
	EXCLAMATION_TRIANGLE = 'EXCLAMATION_TRIANGLE',
	ANGLE_RIGHT = 'ANGLE_RIGHT',
	HOME = 'HOME',
	BOOKMARK = 'BOOKMARK',
	SITEMAP = 'SITEMAP',
	LIST = 'LIST',
	SYNC = 'SYNC',
	COG = 'COG'

}
