export * from './bookmarks.table';
export * from './configuration.table';
export * from './entity.table';
export * from './key-value.table';
export * from './logs.table';
export * from './notes-content.table';
export * from './notes.table';
export * from './quotes.table';
export * from './words.table';
